# Generated by Django 2.1.1 on 2018-10-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=500)),
                ('facility', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('local', models.CharField(max_length=50)),
                ('discription', models.TextField(max_length=1000)),
                ('camp', models.ManyToManyField(to='app.Camp')),
            ],
        ),
    ]
