# Generated by Django 2.1.1 on 2018-10-25 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(1800)]),
        ),
    ]
